### ISSUE TITLE
ParentNode.children属性不是符合W3C标准规范的属性

### ISSUE THREAD

**Issue by AlexZhong22c** [giscafer/ife-course-demo#1]
斌斌学院js任务三
ParentNode.children属性不是符合W3C标准规范的属性，我个人认为用Node.childNodes取代它比较好一点

**Comment by giscafer** [comment]
children是Element的属性，childNodes是Node的属性

Node是Element的父类。

https://developer.mozilla.org/en-US/docs/Web/API/Element

Element的children[0]仍为Element，是Node和Element的实例，Node的childNdoes[0]为Node，只是Node的实例，不是Element的实例。

只要清楚操作对象是什么类型的实例就可以了，用什么都可以。参考博客：http://www.cnblogs.com/jscode/archive/2012/09/04/2670819.html
